language: haskell

env:
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install zsh cabal-install-1.18 ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - cabal install either semigroupoids transformers # examples dependencies

install:
 - cabal update
 - cabal install --only-dependencies --enable-tests
